### ISSUE TITLE
Handle path with `m/x/x'/` notation

### ISSUE THREAD

**Issue by darosior** [darosior/python-bip32#1]
We handle paths with a list of indexes, it would be nice to have a high-level function which translates the `m/x/x'/x` notation to such a list.

**Comment by henriquetft** [comment]
Hello,
What do you prefer, new methods to receive str instead of list, or change the existing ones to handle both types?

**Comment by darosior** [comment]
Hi, I like the `get_XX_from_path()` name : accepting both a `str` or a `list` which can both represent that path is the best option.
