### ISSUE TITLE
Do not glue too tightly to coincurve

### ISSUE THREAD

**Issue by ztane** [darosior/python-bip32#27]
Looks like there is 17.0.0 for which there are prebuilt M1 binaries. But pip now refuses to install it because of the bad constraint in bip32

**Comment by doc-hex** [comment]
I have same issue, except for me it's a system-installed coincurve 16.0.0 that I want

**Comment by darosior** [comment]
Hi, sorry i didn't see that earlier.

Yeah, i'm probably overly conservative with the coincurve version. Happy to take a PR relaxing the requirements, or i'll eventually get to it myself.

**Comment by doc-hex** [comment]
I got you, PR is here:  https://github.com/coinkite/python-bip32/pull/1

**Comment by darosior** [comment]
Cool, can you PR to this repo?

**Comment by darosior** [comment]
Took a shot at this. I don't think we should allow any major version, as major versions may contain breaking changes.

@ztane @doc-hex can you have a look at #40 and let me know whether it fixes your issue? If it does i'll publish a new release.

**Comment by doc-hex** [comment]
I think so, for my case.

**Comment by darosior** [comment]
Alright, merging #27 and releasing version `3.0` now. Please re-open if it is still an issue.

**Comment by darosior** [comment]
Linking https://github.com/darosior/python-bip32/issues/29 for reference.
