### ISSUE TITLE
Expose a `get_fingerprint()` method to the `BIP32` class

### ISSUE THREAD

**Issue by darosior** [darosior/python-bip32#36]
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#user-content-Key_identifiers

**Comment by BenWestgate** [comment]
We should document how to use this in the README.md

I'll do a PR.

**Comment by BenWestgate** [comment]
https://github.com/darosior/python-bip32/pull/45

Documents this method and fixes some typos in the README.md.
