### ISSUE TITLE
SegWit

### ISSUE THREAD

**Issue by engenegr** [darosior/python-bip32#7]
Hey. 

I found out how to work with segwit p2wpkh addresses using this library.

Does it make sense to write tests in according to  https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki and make PR to this library?

**Comment by darosior** [comment]
Hi,

Test vectors are always welcome *for BIP32 derivations*.
This BIP defines also some legacy practices that in my opinion should not be propagated anymore: keys and Bitcoin Script should not be linked and [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md) are a better way to track coins.

More generally, i'd like this repo to stay as minimal as possible both in term of scope and functionalities (only BIP32). :-)

**Comment by engenegr** [comment]
Ok. It will be a custom fork for p2wpkh addresses.
